$ErrorActionPreference = 'Stop'
$utf8 = [System.Text.UTF8Encoding]::new($false)
$nl = [Environment]::NewLine

function Change($id, $phase, $name, $owner, $reviewer, $deps, $why, $scope, $refs, $requirements, $design, $checks) {
    [pscustomobject]@{
        Id = $id; Phase = $phase; Name = $name; Owner = $owner; Reviewer = $reviewer; Dependencies = $deps
        Why = $why; Scope = $scope; References = $refs; Requirements = $requirements; Design = $design; Checks = $checks
    }
}

$backend = @(
    (Change 'BE-001' 'Fase 0: Fundación ejecutable' 'initialize-backend-foundation' 'Jefferson' 'Fátima' 'Ninguna' 'Entregar una API Laravel clonable y verificable antes de implementar dominios.' @('Laravel 13, PHP 8.3 y PostgreSQL','Sanctum, Spatie Permission, Pest y Scribe','estructura modular, configuración y healthcheck') @('docs/architecture/backend.md','docs/decisions/005-technical-foundation.md') @('El backend SHALL instalarse desde un clon sin secretos personales|un clon limpio|se siguen los comandos documentados|la API inicia y las pruebas base pasan','El healthcheck SHALL informar disponibilidad sin revelar secretos|la API está activa|se consulta el healthcheck|responde estado mínimo') @('Crear proyecto Laravel y módulos base','Configurar PostgreSQL, colas, correo y storage privado en .env.example','Instalar dependencias y healthcheck','Agregar pruebas de arranque') @('composer install y Pest pasan','migraciones base aplican y revierten','healthcheck no expone configuración'))
    (Change 'OPS-001' 'Fase 0: Fundación ejecutable' 'initialize-docker-development' 'André' 'Jefferson' 'Ninguna' 'Permitir levantar todo el entorno de forma reproducible.' @('Compose para frontend, backend, PostgreSQL, worker y facial-service','red privada, volúmenes y healthchecks','guía de primer arranque') @('docs/architecture/deployment.md','docs/architecture/deployment-runbook.md','docs/architecture/detailed-system-design.md') @('El entorno SHALL iniciar con un comando documentado|un clon limpio tiene Docker|se ejecuta Compose|los servicios saludables quedan disponibles','PostgreSQL y Python SHALL permanecer en red privada|los servicios están activos|se inspeccionan puertos|no están expuestos a Internet') @('Crear Dockerfiles y Compose','Configurar healthchecks, redes y volúmenes','Preparar facial-service FastAPI mínimo','Documentar operación y diagnóstico') @('docker compose config válido','todos los healthchecks pasan','reinicio conserva PostgreSQL'))
    (Change 'BE-002' 'Fase 0: Fundación ejecutable' 'define-api-contract-conventions' 'Jefferson' 'Fátima' 'BE-001' 'Fijar un contrato HTTP estable para todos los módulos y para frontend.' @('/api/v1, errores, validación y paginación','UUID, fechas, filtros e idempotencia','OpenAPI generado con Scribe') @('docs/architecture/backend.md','docs/security/overview.md') @('La API SHALL responder errores con códigos y estructura estables|una solicitud es inválida|Laravel la procesa|frontend recibe código, mensaje y campos','Los listados SHALL ser paginados|existen más registros que el límite|se consulta el listado|responde datos y metadatos de página') @('Crear response/error conventions','Configurar exception handler y paginación','Definir middleware de idempotencia','Publicar OpenAPI inicial') @('pruebas de errores y paginación pasan','Scribe genera contrato','reintento idempotente no duplica'))
    (Change 'OPS-002' 'Fase 0: Fundación ejecutable' 'configure-backend-quality-ci' 'André' 'Jefferson' 'BE-001, OPS-001' 'Impedir integrar backend roto o sin contrato actualizado.' @('formato, análisis y Pest','smoke de migraciones y OpenAPI','pipeline reproducible') @('docs/architecture/backend.md','docs/architecture/deployment.md') @('CI SHALL rechazar pruebas o migraciones fallidas|un cambio rompe una prueba|se ejecuta pipeline|el pipeline falla con evidencia','CI SHALL comprobar el contrato publicado|un endpoint cambia|se ejecuta pipeline|OpenAPI se regenera o el cambio falla') @('Configurar checks PHP y Pest','Añadir PostgreSQL de CI y smoke de migraciones','Verificar Scribe y secretos','Documentar equivalentes locales') @('pipeline pasa desde clon','fallo intencional bloquea','no aparecen secretos'))
    (Change 'DB-001' 'Fase 1: Identidad y estructura académica' 'add-identity-academic-schema' 'Fátima' 'Jefferson' 'BE-001' 'Crear la base relacional de personas, familias, auditoría y estructura académica.' @('users, alumnos, padres, docentes y administrativos','alumno_padre y audit_logs','periodos, grados, secciones, matrículas, cursos y carga académica') @('docs/architecture/database-schema.md','docs/domain/identity-access.md','docs/domain/academic.md') @('Cada correo humano SHALL ser único|ya existe una cuenta con correo|se intenta crear otra|la base rechaza duplicado','Una matrícula SHALL vincular alumno, sección y periodo|existen entidades válidas|se crea matrícula|queda una pertenencia académica trazable') @('Crear migraciones en orden de FK','Agregar constraints, índices, vigencias y audit_logs','Crear modelos, factories y seeders','Documentar rollback') @('migrate y rollback completos','constraints familiares y académicos pasan','EXPLAIN usa índices principales'))
    (Change 'BE-003' 'Fase 1: Identidad y estructura académica' 'add-human-authentication' 'Jefferson' 'Fátima' 'BE-002, DB-001' 'Permitir acceso humano seguro sin autorregistro.' @('login/logout Sanctum SPA','recuperación por correo','sesión, contextos y expiración') @('docs/security/authentication-authorization.md','docs/domain/identity-access.md') @('El sistema SHALL autenticar la SPA mediante cookie y CSRF|una cuenta activa usa credenciales válidas|inicia sesión|recibe sesión sin token en localStorage','Una cuenta desactivada SHALL perder acceso|una cuenta fue desactivada|intenta usar la API|recibe rechazo genérico') @('Implementar endpoints de sesión y recuperación','Configurar Sanctum stateful, CSRF y cookies','Auditar intentos y logout','Aplicar rate limits') @('login/logout/419 probados','recuperación no filtra existencia','cuenta desactivada rechazada'))
    (Change 'BE-004' 'Fase 1: Identidad y estructura académica' 'add-roles-permissions-account-management' 'Jefferson' 'Fátima' 'BE-003' 'Delegar cuentas y roles sin entregar privilegios sensibles por accidente.' @('CRUD y desactivación de cuentas','roles operativos y permisos específicos','restricciones de superadmin y gestor_usuarios') @('docs/product/roles-and-permissions.md','docs/domain/identity-access.md','docs/security/audit-and-operations.md') @('Solo superadmin SHALL asignar superadmin o gestor_usuarios|un gestor intenta asignarlos|envía el cambio|la operación se rechaza y audita','Gestor de usuarios SHALL administrar roles operativos sin modificar los propios|el gestor edita su cuenta|intenta cambiar roles|la operación se rechaza') @('Crear Policies y casos de uso de cuentas/roles','Sembrar roles y permisos','Auditar cambios sensibles','Exponer endpoints y OpenAPI') @('matriz positiva y negativa pasa','cambios propios bloqueados','desactivación conserva historial'))
    (Change 'BE-005' 'Fase 1: Identidad y estructura académica' 'add-family-links-management' 'Fátima' 'Jefferson' 'BE-004' 'Gestionar relaciones N:M entre padres y alumnos con alcance seguro.' @('crear perfiles padre/alumno','vincular y desvincular familiares','consultar hijos vinculados y contextos') @('docs/domain/identity-access.md','docs/product/roles-and-permissions.md','docs/architecture/database-schema.md') @('Un padre SHALL poder vincularse con varios alumnos|el gestor tiene perfiles válidos|crea vínculos|todos quedan disponibles al padre','Un padre SHALL consultar solo hijos vinculados|solicita un alumno ajeno|consulta el recurso|la Policy responde 404 o 403 sin filtrar datos') @('Implementar casos de uso familiares','Crear Policies por vínculo','Exponer endpoints y resources','Auditar vínculos') @('N:M probado','acceso ajeno bloqueado','desvinculación conserva auditoría'))
    (Change 'BE-006' 'Fase 1: Identidad y estructura académica' 'add-academic-structure-management' 'Fátima' 'Jefferson' 'DB-001, BE-004' 'Administrar la estructura que gobierna horarios, notas y materiales.' @('periodos, grados, secciones, matrículas y cursos','carga académica con vigencia','consultas por docente, alumno y periodo') @('docs/domain/academic.md','docs/architecture/database-schema.md','docs/product/roles-and-permissions.md') @('Coordinación SHALL gestionar estructura académica|coordinador autorizado envía datos válidos|crea la estructura|queda disponible para cargas','Cambiar docente SHALL conservar cargas históricas|una carga vigente cambia|se asigna nuevo docente|la anterior conserva vigencia histórica') @('Crear casos de uso y Policies académicas','Implementar endpoints CRUD y filtros','Proteger cambios con transacciones','Publicar OpenAPI') @('restricciones de vigencia pasan','docente no edita estructura','consultas paginadas usan índices'))
    (Change 'DB-002' 'Fase 2: Facial y asistencia' 'add-biometric-attendance-schema' 'Fátima' 'Jefferson' 'DB-001' 'Persistir consentimiento, estaciones, reconocimientos y asistencia con trazabilidad.' @('consentimientos, perfiles y archivos biométricos','cuentas técnicas, estaciones, cámaras y activaciones','eventos, movimientos, asistencias y anomalías') @('docs/architecture/database-schema.md','docs/architecture/facial-integration.md','docs/security/data-and-files.md') @('Solo SHALL existir un perfil facial activo por persona|una persona ya tiene perfil activo|se activa otro|la base rechaza conflicto','Un movimiento SHALL pertenecer a alumno o docente, nunca ambos|se intenta guardar relación inválida|la transacción ejecuta|constraint rechaza') @('Crear migraciones biométricas y asistencia','Agregar checks e índices parciales','Modelar expiración y revocación','Probar rollback') @('constraints biométricos pasan','índices de pendientes verificados','rollback completo'))
    (Change 'BE-007' 'Fase 2: Facial y asistencia' 'add-biometric-enrollment-consent' 'Jefferson' 'Fátima' 'DB-002' 'Enrolar rostros únicamente con consentimiento y almacenamiento privado.' @('otorgar/revocar consentimiento','enrolamiento de 3 a 5 fotos','perfil activo, eliminación programada y R2 privado') @('docs/security/data-and-files.md','docs/architecture/facial-integration.md','docs/architecture/database-schema.md') @('El sistema SHALL impedir enrolar sin consentimiento otorgado|una persona no consintió|se intenta enrolar|la operación se rechaza','Revocar consentimiento SHALL desactivar el perfil|existe perfil activo|se revoca consentimiento|queda inactivo y se programa eliminación') @('Crear casos de uso de consentimiento/enrolamiento','Integrar storage R2 privado','Cifrar embeddings con clave separada','Auditar y publicar endpoints') @('enrolamiento sin consentimiento bloqueado','revocación desactiva','objetos privados no son públicos'))
    (Change 'BE-008' 'Fase 2: Facial y asistencia' 'add-facial-service-integration' 'André' 'Jefferson' 'OPS-001, DB-002' 'Integrar Laravel con Python sin delegar reglas de asistencia.' @('FastAPI privado de salud, reconocimiento y sincronización','calidad, prueba de vida y umbrales','timeout, autenticación interna y perfiles en memoria') @('docs/architecture/facial-integration.md','docs/architecture/detailed-system-design.md','docs/security/authentication-authorization.md') @('Python SHALL devolver identidad, confianza y prueba de vida sin registrar asistencia|recibe captura autenticada|procesa reconocimiento|devuelve resultado mínimo','Laravel SHALL tratar timeout como evento no automático|Python excede 5 segundos|Laravel espera respuesta|ofrece revisión o alternativa manual') @('Implementar cliente Laravel y API FastAPI','Autenticar red privada y sincronización','Aplicar timeout y circuit handling','Agregar pruebas de contrato') @('contrato Laravel/Python pasa','servicio no accede PostgreSQL','timeout no crea asistencia'))
    (Change 'BE-009' 'Fase 2: Facial y asistencia' 'add-web-station-management' 'André' 'Jefferson' 'BE-004, DB-002, BE-008' 'Activar y revocar navegadores de asistencia sin compartir sesiones humanas.' @('crear estación/cámaras','QR o código de un uso por 10 minutos','sesión técnica limitada, rotación y revocación') @('docs/architecture/facial-integration.md','docs/security/authentication-authorization.md','docs/decisions/002-web-attendance-stations.md') @('Una activación SHALL ser de un solo uso y expirar|el código fue usado o venció|se intenta activar|Laravel rechaza','Una estación SHALL acceder solo a captura y estado mínimo|sesión técnica intenta consultar notas|llama endpoint humano|Policy rechaza') @('Crear casos de uso de estaciones y cámaras','Emitir activación y cookie técnica','Restringir abilities y rutas','Auditar rotación/revocación') @('código usado dos veces falla','estación revocada pierde acceso','rutas humanas bloqueadas'))
    (Change 'BE-010' 'Fase 2: Facial y asistencia' 'add-student-attendance-events' 'Jefferson' 'Fátima' 'BE-008, BE-009' 'Convertir capturas válidas en entradas, salidas y reingresos de alumnos.' @('idempotencia y modo de cámara','alternancia bidireccional','tardanza, salidas de emergencia y notificaciones') @('docs/domain/attendance.md','docs/domain/use-case-catalog.md','docs/architecture/facial-integration.md') @('El primer evento bidireccional SHALL ser ingreso y los siguientes alternar|un alumno no tiene eventos hoy|pasa dos veces|se registran ingreso y salida','Una salida de emergencia SHALL ser manual y notificar al padre|auxiliar registra emergencia|confirma salida|queda movimiento auditado y notificación') @('Implementar procesador de eventos alumno','Aplicar idempotencia, modos y horarios','Crear notificaciones en cola','Exponer historial autorizado') @('duplicado no crea movimiento','alternancia y modo fijo probados','padre recibe solo eventos de hijos'))
    (Change 'BE-011' 'Fase 2: Facial y asistencia' 'add-student-attendance-closure-review' 'Jefferson' 'Fátima' 'BE-010' 'Cerrar jornadas y resolver excepciones sin inventar movimientos.' @('generar faltas al cierre completo','anomalía de ingreso sin salida','revisión dudosa, corrección y justificación','alerta por faltas injustificadas') @('docs/domain/attendance.md','docs/domain/use-case-catalog.md','docs/security/audit-and-operations.md') @('La falta SHALL generarse al cierre solo si no hubo ingreso|terminó la jornada y alumno no ingresó|corre cierre|se crea falta','El sistema SHALL no inventar salida faltante|hay ingreso sin salida|cierra jornada|crea anomalía para Auxiliar') @('Crear jobs de cierre y alertas','Implementar revisión/corrección auditada','Autorizar Auxiliar y TOE para justificar','Manejar eventos capturados antes del cierre') @('cierre tardío corrige falta','solo injustificadas cuentan alerta','salida faltante genera anomalía'))
    (Change 'BE-012' 'Fase 2: Facial y asistencia' 'add-teacher-attendance-sessions' 'Fátima' 'Jefferson' 'BE-006, BE-010' 'Relacionar asistencia docente con clases programadas, cancelaciones y sustitutos.' @('sesiones de clase y primera clase','falta al terminar clase','cancelación por coordinación y sustitución','correcciones por Yanina') @('docs/domain/attendance.md','docs/domain/use-case-catalog.md','docs/architecture/database-schema.md') @('Una clase cancelada SHALL no generar falta|coordinación cancela sesión|termina su horario|no se crea descuento','Una clase sin asistencia SHALL generar falta al finalizar|docente no asistió|termina la clase|queda falta docente') @('Crear sesiones desde horarios','Implementar detección de falta/tardanza','Registrar cancelación y sustituto','Aplicar Policies y auditoría') @('primera/única clase calcula tardanza','cancelación evita falta','docente no corrige su asistencia'))
    (Change 'BE-013' 'Fase 2: Facial y asistencia' 'add-teacher-payroll-liquidation' 'Fátima' 'Jefferson' 'BE-012' 'Calcular y cerrar descuentos docentes con tarifas históricas.' @('tarifas vigentes futuras','descuentos por tardanza y faltas','liquidación mensual revisada y cerrada') @('docs/domain/attendance.md','docs/domain/use-case-catalog.md','docs/architecture/database-schema.md') @('Cambiar tarifa SHALL afectar solo periodos futuros|existe liquidación histórica|Yanina cambia tarifa|histórico conserva monto','Cerrar liquidación SHALL congelar resultados|Yanina revisó el mes|confirma cierre|ya no admite edición directa') @('Implementar tarifas con vigencia','Calcular fórmulas de descuento','Crear revisión y cierre transaccional','Generar reporte de planilla') @('fórmulas justificadas/injustificadas pasan','tarifa histórica inmutable','cierre bloquea cambios'))
    (Change 'DB-003' 'Fase 3: Finanzas' 'add-finance-schema' 'Fátima' 'Jefferson' 'DB-001' 'Persistir configuración, beneficios, obligaciones y movimientos financieros inmutables.' @('configuraciones y conceptos versionados','beneficios por modalidad y alcance','obligaciones congeladas y movimientos') @('docs/domain/finance.md','docs/architecture/database-schema.md','docs/decisions/003-finance-history.md') @('Una obligación SHALL congelar montos y fecha límite|se genera una deuda|se guarda|cambios futuros no alteran sus valores','Una referencia SHALL ser única por medio/proveedor|ya existe referencia|se registra otro pago|la base rechaza') @('Crear migraciones financieras','Agregar checks, FKs, índices y unicidad','Modelar estados e inmutabilidad','Probar consultas y rollback') @('constraints de montos pasan','referencias duplicadas fallan','rollback completo'))
    (Change 'BE-014' 'Fase 3: Finanzas' 'add-finance-configuration-benefits' 'Jefferson' 'Fátima' 'BE-004, DB-003' 'Permitir que la cuenta financiera configure montos y beneficios futuros.' @('conceptos, montos y fechas por periodo','beca, descuento o exoneración','alcance, vigencia y acumulación') @('docs/domain/finance.md','docs/domain/use-case-catalog.md','docs/product/roles-and-permissions.md') @('Solo gestionar_finanzas SHALL modificar configuración|administrativo sin permiso intenta cambiar monto|envía solicitud|se rechaza','Un beneficio SHALL definir modalidad, valor, alcance y vigencia|Yanina crea beneficio válido|confirma|queda disponible para obligaciones futuras') @('Crear casos de uso de configuración/beneficios','Validar modalidades y acumulación','Versionar cambios futuros','Auditar y publicar endpoints') @('permiso específico probado','beneficio inválido rechazado','cambio no altera históricos'))
    (Change 'BE-015' 'Fase 3: Finanzas' 'add-obligation-generation-adjustments' 'Jefferson' 'Fátima' 'BE-014' 'Generar y ajustar deudas pendientes conservando el historial.' @('generación individual/masiva','selección de beneficio y pronto pago','ajuste pendiente con motivo y notificación') @('docs/domain/finance.md','docs/domain/use-case-catalog.md','docs/security/audit-and-operations.md') @('Generar obligación SHALL congelar beneficio y montos aplicables|existe configuración vigente|se generan deudas|cada deuda conserva snapshot','Una deuda pagada SHALL ser inmutable|Yanina intenta ajustarla|envía cambio|se rechaza') @('Implementar generación transaccional','Resolver beneficio único y acumulación','Crear ajuste individual/masivo auditado','Notificar afectados') @('generación masiva no queda parcial','pagada/anulada no cambia','pronto pago congelado'))
    (Change 'BE-016' 'Fase 3: Finanzas' 'add-payment-movements-receipts' 'Jefferson' 'Fátima' 'BE-015' 'Registrar pagos completos y correcciones como movimientos inmutables.' @('pago exacto por efectivo, transferencia, Yape, Plin u otro','recibo secuencial y comprobante privado','anulación y devolución sin borrar historial') @('docs/domain/finance.md','docs/domain/use-case-catalog.md','docs/security/data-and-files.md') @('El pago SHALL ser completo por monto aplicable|una obligación exige 450 hoy|se intenta pagar otro monto|se rechaza','Corregir pago SHALL crear movimiento compensatorio|un pago fue aplicado mal|Yanina anula|original permanece y se registra anulación') @('Implementar registro de pago transaccional','Calcular monto exigible por fecha','Generar recibo PDF y guardar comprobante privado','Implementar anulación/devolución') @('pagos parciales rechazados','referencia duplicada rechazada','historial permanece inmutable'))
    (Change 'BE-017' 'Fase 3: Finanzas' 'add-finance-queries-reminders' 'André' 'Jefferson' 'BE-016' 'Entregar estados de cuenta, morosidad, caja y recordatorios con alcance correcto.' @('estado de cuenta de alumno/padre','morosos y reporte de caja','recordatorios por panel y correo') @('docs/domain/finance.md','docs/domain/use-case-catalog.md','docs/product/roles-and-permissions.md') @('Un padre SHALL ver solo obligaciones de hijos vinculados|consulta estado de hijo ajeno|envía solicitud|se rechaza sin filtrar datos','El estado SHALL mostrar monto pronto pago antes del límite|la obligación es elegible|se consulta|muestra 450 hasta fecha y 480 después') @('Crear queries optimizadas y resources','Aplicar Policies familiares','Crear jobs de recordatorio','Exponer reportes paginados') @('alcance familiar probado','valores cambian al vencer fecha','EXPLAIN de morosos/caja revisado'))
    (Change 'DB-004' 'Fase 4: Evaluación y contenido' 'add-evaluation-content-schema' 'Fátima' 'Jefferson' 'DB-001' 'Persistir evaluaciones, resultados, reportes, materiales, horarios y comunicación.' @('exámenes, notas y reportes académicos','materiales, horarios y calendario','comunicados, lecturas y notificaciones') @('docs/architecture/database-schema.md','docs/domain/academic.md','docs/domain/incidents-communications.md') @('Una nota SHALL pertenecer a matrícula y examen compatibles|se intenta nota ajena a sección|se guarda|constraint o caso de uso rechaza','Una lectura SHALL ser única por comunicado y usuario|usuario marca dos veces|se persiste|queda un registro') @('Crear migraciones de evaluación/contenido','Agregar estados, checks e índices','Crear factories representativas','Probar rollback') @('constraints académicos pasan','lectura idempotente','índices verificados'))
    (Change 'BE-018' 'Fase 4: Evaluación y contenido' 'add-assessment-management' 'Jefferson' 'Fátima' 'BE-006, DB-004' 'Configurar evaluaciones físicas y su ciclo de revisión.' @('crear examen por carga/grado/canal','puntaje máximo y estados','cerrar y reabrir auditadamente') @('docs/domain/academic.md','docs/domain/use-case-catalog.md') @('Coordinación SHALL crear evaluaciones válidas|define examen para carga activa|guarda|queda en borrador','Una evaluación cerrada SHALL cambiar solo tras reapertura auditada|docente intenta editar cerrada|envía cambio|se rechaza') @('Crear entidad y casos de uso de evaluación','Validar canal y puntaje','Aplicar Policies de coordinación/docente','Auditar cierre/reapertura') @('canales y estados probados','docente no crea fuera de carga','cerrada bloquea edición'))
    (Change 'BE-019' 'Fase 4: Evaluación y contenido' 'add-result-entry-import' 'Jefferson' 'Fátima' 'BE-018' 'Registrar resultados procesados manualmente sin que el sistema tome exámenes.' @('registro individual docente','previsualización e importación masiva atómica','estados ausente, exonerado y pendiente') @('docs/domain/academic.md','docs/domain/use-case-catalog.md') @('Un docente SHALL registrar solo notas de su carga activa|docente usa carga ajena|envía nota|Policy rechaza','La importación SHALL ser atómica|una fila masiva es inválida|se confirma importación|no se guarda ninguna fila') @('Crear casos de uso individual/masivo','Validar puntajes y estados','Implementar preview y transacción','Auditar correcciones') @('carga ajena bloqueada','importación inválida revierte','estados no reciben puntaje indebido'))
    (Change 'BE-020' 'Fase 4: Evaluación y contenido' 'add-result-publication-ranking-reports' 'Jefferson' 'Fátima' 'BE-019' 'Publicar resultados, calcular ranking y producir reportes protegidos.' @('publicar y recalcular ranking','corregir publicado y renotificar','libreta/reporte y consultas alumno/padre') @('docs/domain/academic.md','docs/domain/use-case-catalog.md','docs/product/roles-and-permissions.md') @('Resultados SHALL ser visibles solo publicados o cerrados|evaluación sigue borrador|alumno consulta|no recibe notas','Empates SHALL compartir posición|dos alumnos tienen mismo puntaje|se publica|ambos reciben mismo puesto') @('Implementar publicación transaccional','Calcular ranking excluyendo estados','Crear consultas y reportes PDF','Notificar panel/correo y auditar corrección') @('privacidad alumno/padre pasa','empates y exclusiones pasan','corrección recalcula y notifica'))
    (Change 'BE-021' 'Fase 4: Evaluación y contenido' 'add-materials-management' 'André' 'Jefferson' 'BE-006, DB-004' 'Publicar recursos académicos privados para matrículas autorizadas.' @('subir archivo o enlace','editar, reemplazar y eliminar','listar/descargar por carga y matrícula') @('docs/domain/use-case-catalog.md','docs/security/data-and-files.md','docs/domain/academic.md') @('Solo matrícula activa SHALL descargar material|alumno ajeno solicita archivo|consulta endpoint|se rechaza','Archivos SHALL servirse mediante endpoint autorizado|existe material privado|usuario autorizado descarga|recibe stream o URL corta') @('Crear casos de uso y Policies','Validar MIME/tamaño/integridad','Guardar en storage privado','Exponer endpoints y auditoría') @('archivo público directo imposible','matrícula inactiva bloqueada','validación de upload pasa'))
    (Change 'BE-022' 'Fase 4: Evaluación y contenido' 'add-schedules-calendar-management' 'André' 'Jefferson' 'BE-006, DB-004' 'Administrar horarios, calendario y días no laborables.' @('horario semanal por sección/docente','eventos de calendario','días no laborables y consultas familiares') @('docs/domain/academic.md','docs/domain/use-case-catalog.md','docs/architecture/database-schema.md') @('Coordinación SHALL gestionar horarios|coordinador guarda horario válido|confirma|queda consultable por actores vinculados','Un padre SHALL ver horario del hijo vinculado|consulta hijo ajeno|envía solicitud|se rechaza') @('Crear casos de uso de horarios/calendario','Validar solapamientos y alcance','Exponer vistas por actor','Integrar sesiones de clase') @('solapamiento inválido rechazado','alcance familiar probado','día no laboral afecta sesiones'))
    (Change 'BE-023' 'Fase 4: Evaluación y contenido' 'add-communications-notifications' 'André' 'Jefferson' 'BE-004, DB-004' 'Publicar comunicaciones segmentadas y registrar su entrega/lectura.' @('comunicado por rol, periodo, grado o sección','notificación de panel y correo','lectura y archivo') @('docs/domain/incidents-communications.md','docs/domain/use-case-catalog.md','docs/architecture/database-schema.md') @('Un usuario SHALL recibir solo comunicados de su segmento|se publica para otro grado|usuario consulta|no aparece','Marcar leído SHALL ser idempotente|usuario abre comunicado varias veces|marca lectura|queda una lectura') @('Crear segmentación y queries','Enviar notificaciones por cola','Registrar lectura/archivo','Aplicar permisos de publicación') @('segmentación probada','lectura idempotente','fallo de correo reintentable'))
    (Change 'DB-005' 'Fase 5: Incidencias y Psicología' 'add-incidents-psychology-schema' 'Fátima' 'Jefferson' 'DB-001' 'Persistir incidencias, historial y atenciones privadas con separación clara.' @('incidencias e historial inmutable','atenciones psicológicas privadas','archivos y estados de derivación') @('docs/architecture/database-schema.md','docs/domain/incidents-communications.md','docs/security/data-and-files.md') @('El historial SHALL conservar cada acción|una incidencia cambia estado|se persiste|se agrega historial sin borrar anterior','Notas privadas SHALL permanecer separadas de incidencia general|TOE consulta incidencia|recibe datos|no incluye notas psicológicas') @('Crear migraciones e índices','Separar campos privados','Agregar FKs y estados','Probar rollback y privacidad') @('historial no se elimina','queries generales excluyen privado','rollback completo'))
    (Change 'BE-024' 'Fase 5: Incidencias y Psicología' 'add-incidents-workflow' 'Jefferson' 'Fátima' 'BE-004, DB-005' 'Implementar el cuaderno de incidencias desde Auxiliar hasta TOE.' @('registrar, comentar y derivar a TOE','notificar padre y resolver','historial y reporte semanal') @('docs/domain/incidents-communications.md','docs/domain/use-case-catalog.md','docs/product/roles-and-permissions.md') @('Auxiliar SHALL registrar y derivar a TOE|auxiliar documenta caso|deriva|TOE puede continuarlo','TOE SHALL notificar al padre vinculado|caso grave requiere aviso|TOE confirma|se crea notificación y correo') @('Crear casos de uso e historial','Aplicar Policies por rol/vínculo','Integrar notificaciones','Crear reporte paginado') @('flujo Auxiliar-TOE pasa','padre ajeno no recibe','acciones quedan auditadas'))
    (Change 'BE-025' 'Fase 5: Incidencias y Psicología' 'add-private-psychology-workflow' 'Jefferson' 'Fátima' 'BE-024' 'Registrar atención psicológica sin exponer notas privadas.' @('derivación TOE a Psicología','atención y notas confidenciales','consulta exclusiva Psicología/superadmin') @('docs/domain/incidents-communications.md','docs/security/authentication-authorization.md','docs/security/audit-and-operations.md') @('Solo Psicología y superadmin SHALL consultar notas privadas|TOE intenta consultar|envía solicitud|se rechaza y no filtra contenido','Acceso sensible SHALL auditarse sin copiar notas|Psicología consulta atención|se autoriza|audit log registra evento sin contenido') @('Crear casos de uso privados','Implementar Policies explícitas','Separar Resources públicos/privados','Auditar accesos sensibles') @('matriz negativa completa','logs no contienen notas','superadmin y Psicología autorizados'))
    (Change 'BE-026' 'Fase 6: Operación y release' 'add-private-files-service' 'André' 'Fátima' 'BE-001' 'Centralizar archivos privados y evitar storage público accidental.' @('uploads privados y descargas autorizadas','URLs firmadas cortas para R2','validación, retención y eliminación') @('docs/security/data-and-files.md','docs/architecture/deployment.md') @('Un archivo privado SHALL requerir autorización|usuario no autorizado conoce identificador|intenta descargar|se rechaza','Evidencia biométrica SHALL expirar|objeto alcanzó expira_en|corre limpieza|se elimina y audita') @('Crear servicio de archivos privados','Validar MIME/tamaño/checksum','Implementar URLs firmadas y limpieza','Agregar Policies y auditoría') @('storage:link no requerido','URL expira','limpieza elimina evidencia'))
    (Change 'BE-027' 'Fase 6: Operación y release' 'harden-security-observability' 'André' 'Fátima' 'BE-003, BE-026' 'Aplicar controles transversales, auditoría y observabilidad antes de producción.' @('rate limits, headers y reautenticación','audit logs y correlación','métricas y alertas sin datos sensibles') @('docs/security/overview.md','docs/security/audit-and-operations.md','docs/architecture/deployment.md') @('Logs SHALL excluir secretos, biometría y notas privadas|ocurre operación sensible|se registra log|solo contiene metadatos permitidos','Operaciones sensibles SHALL quedar auditadas|se ajusta deuda o rol|termina operación|existe evento trazable') @('Configurar controles HTTP y rate limits','Instrumentar auditoría y correlación','Agregar métricas/alertas','Revisar redacción de datos') @('escaneo de logs sin sensibles','rate limits probados','eventos críticos auditados'))
    (Change 'OPS-003' 'Fase 6: Operación y release' 'add-production-deployment-backups' 'André' 'Jefferson' 'OPS-002, BE-008' 'Desplegar y recuperar el sistema completo de forma documentada.' @('Nginx, Laravel, worker, scheduler, PostgreSQL, frontend y Python','backups cifrados fuera del VPS','restauración RPO 24h/RTO 4h') @('docs/architecture/deployment.md','docs/architecture/deployment-runbook.md') @('Producción SHALL exponer solo HTTPS necesario|stack está desplegado|se inspeccionan puertos|DB y Python siguen privados','Backup SHALL restaurar datos y archivos|existe respaldo cifrado|se prueba restauración|el sistema recupera alcance definido') @('Crear configuración producción y secretos externos','Automatizar backup integral y checksums','Documentar restore y rollback','Probar restauración aislada') @('puertos privados verificados','restore trimestral documentado','alerta ante backup fallido'))
    (Change 'BE-028' 'Fase 6: Operación y release' 'verify-backend-release' 'Jefferson' 'André' 'BE-013, BE-017, BE-020, BE-023, BE-025, BE-027, OPS-003' 'Demostrar que backend cubre todos los dominios y puede salir a producción.' @('regresión completa y autorización negativa','rendimiento y OpenAPI','migración, backup y operación') @('docs/README.md','docs/product/approved-requirements.md','docs/security/overview.md') @('El release SHALL cumplir todos los escenarios aceptados|todas las specs están archivadas|se ejecuta verificación|no quedan fallos críticos','OpenAPI SHALL representar endpoints liberados|se genera contrato final|se compara con implementación|no hay divergencias') @('Ejecutar suite completa','Revisar matriz de permisos y rendimiento','Validar OpenAPI, migraciones y backups','Registrar pendientes explícitos') @('suite y contrato pasan','sin vulnerabilidades críticas','restore y smoke producción pasan'))
)

$frontend = @(
    (Change 'FE-001' 'Fase 0: Fundación ejecutable' 'initialize-vite-frontend-foundation' 'Vincenzo' 'Kiara' 'Ninguna' 'Entregar una SPA clonable con estructura y dependencias aprobadas.' @('React, TypeScript y Vite','Tailwind, shadcn/ui y Phosphor Icons','Query, Axios, forms, Zod, Zustand, Recharts, GSAP y pruebas') @('docs/architecture/frontend.md','docs/decisions/004-frontend-foundation.md','docs/decisions/005-technical-foundation.md') @('Frontend SHALL instalar, probar y compilar desde un clon|un clon limpio tiene Node compatible|ejecuta comandos documentados|la SPA inicia y build termina','Frontend SHALL usar Phosphor Icons como única librería|se crea componente con icono|se implementa|importa Phosphor Icons') @('Crear proyecto y estructura por features','Instalar dependencias aprobadas','Configurar alias, env tipado y página base','Agregar smoke tests') @('install/build/test pasan','Phosphor Icons es la única librería de iconos','arranque no muestra errores'))
    (Change 'FE-002' 'Fase 0: Fundación ejecutable' 'add-design-system-layouts' 'Kiara' 'Vincenzo' 'FE-001' 'Crear una base visual consistente, responsive y accesible.' @('tokens y componentes shadcn adaptados','PublicLayout, PortalLayout y StationLayout','estados loading, vacío, error y sin permiso') @('docs/architecture/frontend.md','docs/product/roles-and-permissions.md') @('Cada pantalla SHALL soportar estados operativos|una consulta carga, falla o queda vacía|se renderiza|muestra estado accesible','Interfaz SHALL respetar reducción de movimiento|usuario activa reduced motion|navega|animación no bloquea ni distrae') @('Crear tokens y componentes base','Implementar layouts y navegación responsive','Configurar Phosphor Icons y patrones de estados','Documentar uso de GSAP') @('WCAG básica pasa','responsive móvil/tablet/escritorio','reduced motion probado'))
    (Change 'FE-003' 'Fase 0: Fundación ejecutable' 'add-api-client-routing-auth' 'Vincenzo' 'Kiara' 'FE-001, Backend BE-002/BE-003' 'Conectar la SPA con Sanctum y separar contextos humanos y técnicos.' @('Axios CSRF/withCredentials y TanStack Query','login, recuperación, selección de contexto y logout','rutas públicas, portal, admin y estación','ProtectedRoute, PermissionRoute y manejo 401/403/419') @('docs/security/authentication-authorization.md','docs/architecture/frontend.md','docs/architecture/facial-integration.md') @('La SPA SHALL autenticarse sin guardar tokens en localStorage|usuario inicia sesión|frontend obtiene CSRF y autentica|la sesión usa cookie','Una estación SHALL no navegar al portal humano|sesión técnica cambia URL|router y API validan|queda bloqueada') @('Crear api client e interceptores','Crear AuthProvider, query client y pantallas de acceso/recuperación','Implementar router/layouts/guards y selección de contexto','Manejar sesión expirada y errores') @('login/logout/recuperación/419 E2E','localStorage sin tokens','estación bloqueada del portal'))
    (Change 'FE-004' 'Fase 0: Fundación ejecutable' 'configure-frontend-quality-e2e' 'Vincenzo' 'Kiara' 'FE-001, FE-002' 'Detectar regresiones visuales, funcionales y de accesibilidad.' @('lint, format, typecheck y build','Vitest/Testing Library','Playwright de flujos críticos') @('docs/architecture/frontend.md','docs/architecture/deployment.md') @('CI SHALL rechazar errores de tipos, pruebas o build|un cambio rompe TypeScript|se ejecuta pipeline|el pipeline falla','E2E SHALL comprobar rutas y estados críticos|existe entorno reproducible|se ejecutan pruebas|se verifican flujos definidos') @('Configurar herramientas y CI','Crear helpers de pruebas','Añadir chequeos de consola/accesibilidad','Documentar ejecución local') @('pipeline desde clon pasa','error de consola detectado','Playwright ejecuta responsive'))
    (Change 'FE-005' 'Fase 1: Identidad y academia' 'add-account-role-administration' 'Kiara' 'Vincenzo' 'FE-002, FE-003, Backend BE-004' 'Permitir administrar cuentas y roles respetando restricciones.' @('listado y formulario de cuentas','activar/desactivar y asignar roles operativos','estados sin permiso y confirmaciones') @('docs/domain/identity-access.md','docs/product/roles-and-permissions.md') @('Gestor SHALL administrar roles operativos|gestor abre una cuenta|edita rol permitido|la UI confirma resultado','UI SHALL ocultar y bloquear privilegios no permitidos|gestor intenta asignar superadmin|usa formulario|la opción no existe y backend se respeta') @('Crear rutas/páginas de cuentas','Crear formularios Zod y permisos visuales','Implementar queries/mutations e invalidación','Añadir confirmaciones y auditoría visible') @('matriz visual probada','errores backend visibles','responsive y teclado pasan'))
    (Change 'FE-006' 'Fase 1: Identidad y academia' 'add-family-links-administration' 'Kiara' 'Vincenzo' 'FE-003, Backend BE-005' 'Gestionar perfiles y vínculos familiares sin autorregistro.' @('crear padre/alumno','vincular/desvincular N:M','mostrar hijos/padres relacionados') @('docs/domain/identity-access.md','docs/product/roles-and-permissions.md') @('Gestor SHALL vincular varios padres e hijos|abre perfil alumno|selecciona padres|los vínculos quedan visibles','UI SHALL confirmar desvinculación|gestor retira vínculo|confirma acción|lista se actualiza') @('Crear páginas y buscadores familiares','Implementar formularios y diálogo de vínculo','Conectar queries/mutations','Cubrir estados y permisos') @('N:M visible correctamente','desvinculación confirmada','sin autorregistro expuesto'))
    (Change 'FE-007' 'Fase 1: Identidad y academia' 'add-academic-structure-administration' 'Kiara' 'Vincenzo' 'FE-002, FE-003, Backend BE-006' 'Administrar periodos, grados, secciones, matrículas, cursos y cargas.' @('navegación académica','CRUD y asignaciones','vigencias e historial de carga') @('docs/domain/academic.md','docs/product/roles-and-permissions.md') @('Coordinación SHALL gestionar estructura desde panel|abre módulo académico|crea entidades válidas|listas se actualizan','Cambio de docente SHALL mostrar vigencia|coordinación reasigna carga|confirma|histórico permanece visible') @('Crear páginas académicas y DataTables','Crear formularios y selectores dependientes','Implementar queries/mutations','Mostrar vigencia y errores') @('flujos CRUD E2E','roles no autorizados bloqueados','tablas responsive'))
    (Change 'FE-008' 'Fase 1: Identidad y academia' 'add-family-student-portal-shell' 'Vincenzo' 'Kiara' 'FE-003, Backend BE-005/BE-006/BE-007' 'Dar a padres y alumnos un portal de consulta con contexto seguro.' @('selector de hijo/contexto','inicio con accesos permitidos','historial y navegación solo lectura','estado de consentimiento/perfil biométrico sin exponer datos') @('docs/product/roles-and-permissions.md','docs/domain/identity-access.md','docs/domain/incidents-communications.md','docs/security/data-and-files.md') @('Un padre SHALL cambiar entre hijos vinculados|padre tiene varios hijos|elige otro contexto|panel muestra solo ese hijo','Alumno SHALL ver únicamente contexto propio|alumno navega portal|consulta módulos|no puede cambiar a otro alumno','Familia SHALL consultar solo estado biométrico|padre abre estado de hijo|consulta|ve activo/inactivo sin fotos ni embedding') @('Crear portal y selector de contexto','Implementar navegación por permisos','Mostrar estado biométrico mínimo sin datos sensibles','Persistir contexto sin datos sensibles y cubrir estados') @('contextos E2E','rutas de escritura ausentes','estado biométrico no expone datos','acceso ajeno bloqueado'))
    (Change 'FE-009' 'Fase 2: Facial y asistencia' 'add-web-station-activation-capture' 'Vincenzo' 'Kiara' 'FE-003, Backend BE-009/BE-010' 'Operar estaciones web limitadas en celular, tablet o PC multicámara.' @('activar con QR/código','seleccionar cámaras y modo','captura, resultado, timeout y estado revocado') @('docs/architecture/facial-integration.md','docs/decisions/002-web-attendance-stations.md') @('Estación SHALL activarse sin sesión humana|equipo recibe código válido|lo ingresa|abre captura técnica','PC SHALL seleccionar varias cámaras|navegador detecta cámaras|responsable configura|cada una muestra modo y estado') @('Crear rutas StationLayout','Implementar activación y permisos de cámara','Crear captura e idempotency key','Mostrar éxito, revisión, rechazo, timeout y revocación') @('E2E activación un uso','multicámara probado','retroceso no abre portal'))
    (Change 'FE-009A' 'Fase 2: Facial y asistencia' 'add-biometric-station-administration' 'Kiara' 'Vincenzo' 'FE-003, Backend BE-007/BE-009' 'Administrar consentimiento, enrolamiento y dispositivos sin acceder a datos biométricos crudos.' @('otorgar/revocar consentimiento y enrolar con 3 a 5 fotos','listar/crear/revocar estaciones y cámaras','generar activación temporal y revisar estado') @('docs/architecture/facial-integration.md','docs/security/data-and-files.md','docs/product/roles-and-permissions.md') @('Gestor autorizado SHALL enrolar solo con consentimiento|persona no consintió|intenta iniciar enrolamiento|UI y API lo bloquean','Gestor SHALL revocar una estación comprometida|selecciona estación activa|confirma revocación|queda inactiva y visible en historial') @('Crear panel biométrico y de dispositivos','Crear flujo guiado de consentimiento/enrolamiento','Crear gestión de estación/cámaras y activación','Evitar mostrar embeddings o URLs permanentes') @('enrolamiento sin consentimiento bloqueado','revocación E2E','datos biométricos no aparecen en UI/consola'))
    (Change 'FE-010' 'Fase 2: Facial y asistencia' 'add-student-attendance-supervision' 'Kiara' 'Vincenzo' 'FE-002, FE-003, Backend BE-011' 'Permitir al Auxiliar supervisar jornadas y resolver excepciones.' @('tablero de eventos y anomalías','revisión dudosa y corrección','salida de emergencia, falta y justificación') @('docs/domain/attendance.md','docs/product/roles-and-permissions.md') @('Auxiliar SHALL resolver reconocimiento dudoso|evento queda pendiente|auxiliar confirma o rechaza|tablero refleja decisión','UI SHALL no inventar salida|hay ingreso sin salida|auxiliar revisa anomalía|debe registrar motivo y hora real') @('Crear dashboard y filtros','Crear flujos de revisión/corrección','Implementar salida emergencia y justificación','Mostrar historial auditado') @('flujos E2E pasan','acciones requieren motivo','roles ajenos bloqueados'))
    (Change 'FE-011' 'Fase 2: Facial y asistencia' 'add-teacher-attendance-payroll' 'Kiara' 'Vincenzo' 'FE-003, Backend BE-012/BE-013' 'Permitir a Yanina revisar asistencia docente y cerrar planilla.' @('asistencia, clases canceladas y sustitutos','tarifas y descuentos','revisión/cierre y reporte mensual') @('docs/domain/attendance.md','docs/domain/use-case-catalog.md') @('Yanina SHALL ver cálculo explicable|existe tardanza o falta|abre liquidación|ve fórmula, tarifa y monto','Cerrar SHALL requerir confirmación explícita|liquidación está revisada|Yanina confirma|UI queda en solo lectura') @('Crear panel docente/planilla','Crear formularios de tarifa/corrección/sustituto','Mostrar desglose y estados','Implementar cierre y reporte') @('fórmulas visibles','cierre bloquea UI','permiso gestionar_planilla probado'))
    (Change 'FE-012' 'Fase 3: Finanzas' 'add-finance-configuration-benefits' 'Kiara' 'Vincenzo' 'FE-003, Backend BE-014' 'Dar a Yanina control de configuración y beneficios futuros.' @('conceptos, montos y fechas','becas/descuentos/exoneraciones','alcance, vigencia y acumulación') @('docs/domain/finance.md','docs/product/roles-and-permissions.md') @('Cuenta financiera SHALL configurar valores futuros|Yanina edita periodo|confirma|muestra nueva versión','Formulario SHALL explicar alcance y acumulación|Yanina crea beneficio|selecciona conceptos/vigencia|preview muestra aplicación') @('Crear páginas de configuración','Crear formularios Zod y previews','Implementar permisos e invalidación','Mostrar historial/versiones') @('solo gestionar_finanzas accede','validaciones visibles','histórico diferenciable'))
    (Change 'FE-013' 'Fase 3: Finanzas' 'add-obligations-payments-administration' 'Kiara' 'Vincenzo' 'FE-003, Backend BE-015/BE-016' 'Gestionar obligaciones, ajustes y pagos manuales sin alterar históricos.' @('generar/ajustar pendientes','registrar pago completo y comprobante','anular/devolver y generar recibo') @('docs/domain/finance.md','docs/domain/use-case-catalog.md') @('UI SHALL impedir pago parcial|obligación exige monto exacto|Yanina registra pago|campo exige valor aplicable','Ajuste SHALL exigir motivo y mostrar afectados|Yanina ajusta grupo|previsualiza|confirma con motivo') @('Crear DataTables y filtros financieros','Crear generación/ajuste con preview','Crear registro pago y comprobante','Crear anulación/devolución y recibo') @('pago parcial imposible','acciones históricas confirmadas','upload y errores probados'))
    (Change 'FE-014' 'Fase 3: Finanzas' 'add-finance-state-portals' 'Vincenzo' 'Kiara' 'FE-008, Backend BE-017' 'Mostrar estado de cuenta comprensible a familias y reportes a Yanina.' @('estado por alumno/hijo','pronto pago y vencimiento','morosos, caja y recordatorios') @('docs/domain/finance.md','docs/product/roles-and-permissions.md') @('Portal SHALL mostrar ambos montos antes del límite|deuda es elegible|familia consulta|ve 450 hasta fecha y 480 después','Padre SHALL ver solo hijos vinculados|cambia contexto|consulta estado|muestra únicamente el hijo seleccionado') @('Crear estado de cuenta responsive','Crear vistas morosos/caja autorizadas','Mostrar recibos y estados','Integrar selector familiar') @('montos por fecha probados','alcance familiar E2E','sin acciones de pago online'))
    (Change 'FE-015' 'Fase 4: Evaluación y contenido' 'add-assessment-result-entry' 'Vincenzo' 'Kiara' 'FE-003, Backend BE-018/BE-019' 'Permitir configurar evaluaciones y cargar resultados procesados.' @('evaluaciones para coordinación','registro individual docente','preview e importación masiva') @('docs/domain/academic.md','docs/domain/use-case-catalog.md') @('Docente SHALL cargar solo sus cursos|abre registro|selecciona carga|solo aparecen asignadas','Importación SHALL mostrar errores antes de confirmar|archivo contiene error|se previsualiza|no permite confirmar hasta corregir') @('Crear páginas de evaluaciones','Crear tabla editable de notas','Crear importador con preview','Mostrar estados y permisos') @('carga ajena ausente','preview errores probado','teclado y tabla responsive'))
    (Change 'FE-016' 'Fase 4: Evaluación y contenido' 'add-result-publication-reports-portals' 'Vincenzo' 'Kiara' 'FE-008, Backend BE-020' 'Publicar, corregir y consultar resultados/rankings protegidos.' @('revisión/publicación/cierre coordinación','corrección publicada auditada','notas, ranking y reportes familia/alumno') @('docs/domain/academic.md','docs/product/roles-and-permissions.md') @('Notas SHALL ocultarse antes de publicación|evaluación está borrador|familia consulta|no ve resultados','Corrección publicada SHALL advertir recálculo/notificación|coordinación corrige|abre diálogo|ve impacto antes de confirmar') @('Crear panel publicación/cierre','Crear diálogo corrección auditada','Crear portales de resultados/ranking','Integrar descarga de reportes') @('visibilidad por estado pasa','alcance familiar E2E','confirmaciones accesibles'))
    (Change 'FE-017' 'Fase 4: Evaluación y contenido' 'add-materials-portal' 'Kiara' 'Vincenzo' 'FE-002, Backend BE-021' 'Publicar y consultar materiales según carga/matrícula.' @('gestión docente/coordinación','lista por alumno y semana','upload, enlace y descarga privada') @('docs/domain/use-case-catalog.md','docs/security/data-and-files.md') @('Alumno SHALL ver materiales de su matrícula|abre materiales|filtra semana|solo aparecen permitidos','Upload SHALL mostrar validaciones|archivo excede reglas|docente intenta subir|UI muestra error sin perder contexto') @('Crear páginas de gestión y portal','Crear upload/enlace y progreso','Implementar filtros y descarga autorizada','Cubrir estados') @('alcance de matrícula probado','upload inválido visible','descarga privada E2E'))
    (Change 'FE-018' 'Fase 4: Evaluación y contenido' 'add-schedules-calendar-portals' 'Kiara' 'Vincenzo' 'FE-002, Backend BE-022' 'Administrar y consultar horarios/calendario por contexto.' @('editor de horario coordinación','vistas docente, alumno y padre','calendario y días no laborables') @('docs/domain/academic.md','docs/domain/use-case-catalog.md') @('Cada actor SHALL ver su horario permitido|usuario abre horario|consulta|recibe vista de su contexto','Editor SHALL advertir solapamientos|coordinación crea conflicto|intenta guardar|muestra error') @('Crear editor y vistas responsive','Crear calendario mensual','Integrar contexto familiar','Mostrar conflictos/estados') @('vistas por rol pasan','conflicto visible','móvil usable'))
    (Change 'FE-019' 'Fase 4: Evaluación y contenido' 'add-communications-notifications' 'Kiara' 'Vincenzo' 'FE-002, Backend BE-023' 'Publicar, leer y archivar comunicaciones segmentadas.' @('editor y segmentación','bandeja/notificaciones','lectura y archivo') @('docs/domain/incidents-communications.md','docs/product/roles-and-permissions.md') @('Publicador SHALL previsualizar destinatarios|configura segmento|revisa antes de publicar|ve alcance esperado','Usuario SHALL marcar lectura al abrir|abre comunicado|contenido carga|estado cambia a leído') @('Crear editor segmentado','Crear bandeja y contador','Implementar lectura/archivo','Cubrir permisos y estados') @('segmentación E2E','lectura idempotente','roles de publicación probados'))
    (Change 'FE-020' 'Fase 5: Incidencias y Psicología' 'add-incidents-workflow' 'Kiara' 'Vincenzo' 'FE-003, Backend BE-024' 'Operar el cuaderno de incidencias y seguimiento TOE.' @('registro Auxiliar/TOE','derivación, comentarios, notificación y resolución','historial y reporte') @('docs/domain/incidents-communications.md','docs/product/roles-and-permissions.md') @('Auxiliar SHALL registrar y derivar incidencia|crea caso|deriva a TOE|historial muestra ambas acciones','TOE SHALL gestionar seguimiento|abre caso derivado|comenta/notifica/resuelve|estado e historial se actualizan') @('Crear cuaderno y formulario','Crear detalle con timeline','Implementar derivación/notificación/resolución','Aplicar permisos visuales') @('flujo completo E2E','historial visible','padre ve solo lo permitido'))
    (Change 'FE-021' 'Fase 5: Incidencias y Psicología' 'add-private-psychology-portal' 'Kiara' 'Vincenzo' 'FE-003, Backend BE-025' 'Ofrecer un espacio explícitamente privado para Psicología y superadmin.' @('bandeja de derivados','registro y consulta de atención privada','bloqueo total a otros roles') @('docs/domain/incidents-communications.md','docs/security/authentication-authorization.md') @('Portal privado SHALL ser visible solo a Psicología/superadmin|otro rol conoce ruta|navega|muestra sin permiso sin datos','Notas SHALL evitar exposición incidental|Psicología abre listado|se renderiza|resumen no muestra contenido privado innecesario') @('Crear rutas/layout privado','Crear formularios y detalle protegido','Evitar previews sensibles','Cubrir estados y permisos') @('matriz negativa E2E','sin notas en consola/URL','superadmin/Psicología pasan'))
    (Change 'FE-022' 'Fase 6: Calidad y release' 'harden-accessibility-performance' 'Kiara' 'Vincenzo' 'FE-005..FE-021' 'Asegurar que toda la SPA sea usable y eficiente antes del release.' @('WCAG AA y teclado','responsive y reduced motion','lazy loading, caché y tablas grandes') @('docs/architecture/frontend.md','docs/security/overview.md') @('Flujos críticos SHALL operarse con teclado|usuario no usa mouse|recorre flujo|completa acciones con foco visible','Módulos pesados SHALL cargar bajo demanda|usuario entra al portal|carga inicial|no descarga features no visitadas') @('Auditar componentes y rutas','Optimizar bundles/queries/tablas','Corregir foco, contraste y motion','Agregar pruebas automáticas') @('axe sin fallos críticos','presupuesto bundle aceptado','responsive completo'))
    (Change 'FE-023' 'Fase 6: Calidad y release' 'verify-frontend-release-e2e' 'Vincenzo' 'Kiara' 'FE-004, FE-022, Backend BE-028' 'Demostrar los flujos completos de todos los roles antes de liberar.' @('E2E por rol y dominio','contrato backend final','build, consola, accesibilidad y responsive') @('docs/product/approved-requirements.md','docs/architecture/frontend.md','docs/security/overview.md') @('Release SHALL cubrir flujos críticos de cada rol|entorno release está activo|se ejecuta E2E|todos los recorridos pasan','Release SHALL no contener rutas o mocks temporales|se inspecciona build|se navega|usa contratos publicados reales') @('Ejecutar matriz E2E completa','Revisar permisos y contextos','Validar build/accesibilidad/consola','Registrar evidencia y pendientes') @('E2E por rol pasa','sin mocks ni errores consola','móvil/tablet/escritorio pasan'))
)

function WriteText($path, $lines) {
    $parent = Split-Path -Parent $path
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
    $flat = @()
    foreach ($line in $lines) {
        if ($line -is [array]) { $flat += $line } else { $flat += $line }
    }
    [System.IO.File]::WriteAllText($path, ($flat -join $nl) + $nl, $utf8)
}

function GenerateProject($project, $changes) {
    $root = (Resolve-Path $project).Path
    $changeRoot = Join-Path $root 'openspec\changes'
    if (-not $changeRoot.StartsWith($root)) { throw "Ruta insegura: $changeRoot" }
    if (Test-Path $changeRoot) { Remove-Item -LiteralPath $changeRoot -Recurse -Force }
    New-Item -ItemType Directory -Force -Path $changeRoot | Out-Null

    foreach ($c in $changes) {
        $dir = Join-Path $changeRoot $c.Name
        $relativeRefs = $c.References | ForEach-Object { '- `../../../../{0}`' -f $_ }
        WriteText (Join-Path $dir 'proposal.md') @(
            "# Proposal: $($c.Name)", '', "**ID:** $($c.Id)  ", "**Fase:** $($c.Phase)  ", "**Owner:** $($c.Owner)  ",
            "**Reviewer:** $($c.Reviewer)  ", "**Dependencias:** $($c.Dependencies)", '', '## Why', '', $c.Why, '',
            '## In Scope', '', ($c.Scope | ForEach-Object { "- $_" }), '', '## Out of Scope', '',
            '- Capacidades pertenecientes a otros changes.', '- Cambiar reglas compartidas sin actualizar `docs/`.', '',
            '## Impact', '', ('- Proyecto: `{0}`.' -f $project), "- Capacidades: $($c.Scope -join ', ').", '', '## Source Documents', '', $relativeRefs
        )
        WriteText (Join-Path $dir 'design.md') @(
            "# Design: $($c.Name)", '', '## Sources and Invariants', '', ($c.References | ForEach-Object { '- `../../../../{0}`' -f $_ }), '',
            '## Technical Design', '', ($c.Design | ForEach-Object { "- $_." }), '', '## Security and Authorization', '',
            '- Laravel sigue siendo autoridad de permisos y reglas críticas.', '- Aplicar mínimo privilegio, auditoría y protección de datos según los documentos fuente.', '',
            '## Testing Strategy', '', ($c.Checks | ForEach-Object { "- $_." }), '', '## Rejected Scope', '',
            '- No implementar capacidades declaradas en otros changes.', '- No depender de changes activos de otro proyecto como contrato estable.'
        )
        $taskNumber = 1
        $taskLines = @("# Tasks: $($c.Name)", '', '## Implementation')
        foreach ($item in $c.Design) { $taskLines += "- [ ] 1.$taskNumber $item. Owner: $($c.Owner)"; $taskNumber++ }
        $checkNumber = 1
        $taskLines += '', '## Verification'
        foreach ($item in $c.Checks) { $taskLines += "- [ ] 2.$checkNumber Verificar que $item. Owner: $($c.Owner)"; $checkNumber++ }
        $taskLines += '', '## Review and Archive', "- [ ] 3.1 Publicar contratos/documentación afectados. Owner: $($c.Owner)", "- [ ] 3.2 Revisar y archivar la spec aceptada. Reviewer: $($c.Reviewer)"
        WriteText (Join-Path $dir 'tasks.md') $taskLines

        WriteText (Join-Path $dir 'verification.md') @(
            "# Verification: $($c.Name)", '', '## Automated and Manual Checks', '', ($c.Checks | ForEach-Object { "- [ ] $_." }), '',
            '## Required Evidence', '', '- [ ] Resultados de pruebas o comandos adjuntos.', '- [ ] Escenarios de la delta spec demostrados.',
            '- [ ] Permisos negativos y datos sensibles revisados.', '- [ ] Contrato y documentos sincronizados.', '', '## Results', '', 'Pendiente durante la ejecución del change.'
        )
        $spec = @("# $($c.Name) Specification", '', '## Purpose', '', $c.Why, '', '## ADDED Requirements', '')
        $ri = 1
        foreach ($r in $c.Requirements) {
            $parts = $r -split '\|'
            $spec += "### Requirement $ri", '', $parts[0], '', "#### Scenario: $($parts[3])", '', "- GIVEN $($parts[1])", "- WHEN $($parts[2])", "- THEN $($parts[3])", ''
            $ri++
        }
        WriteText (Join-Path $dir "specs\$($c.Name)\spec.md") $spec
    }

    $plan = @("# $([cultureinfo]::CurrentCulture.TextInfo.ToTitleCase($project)) Execution Plan", '', '## Leyenda', '', '- `[ ]` pendiente', '- `[~]` en progreso', '- `[-]` bloqueado', '- `[x]` terminado, verificado y archivado', '')
    foreach ($phase in ($changes | Select-Object -ExpandProperty Phase -Unique)) {
        $plan += "## $phase", '', '| ID | Status | Change | Owner | Reviewer | Dependencies |', '|---|---|---|---|---|---|'
        foreach ($c in $changes | Where-Object Phase -eq $phase) { $plan += ('| {0} | `[ ]` | `{1}` | {2} | {3} | {4} |' -f $c.Id, $c.Name, $c.Owner, $c.Reviewer, $c.Dependencies) }
        $plan += ''
    }
    $plan += '## Regla de ejecución', '', 'Cada change se detalla desde sus documentos fuente antes de implementarse. No se inicia un change bloqueado ni se archiva sin demostrar todos sus escenarios.'
    WriteText (Join-Path $root 'openspec\EXECUTION_PLAN.md') $plan
}

GenerateProject 'backend' $backend
GenerateProject 'frontend' $frontend
